# Generated by Django 4.0.7 on 2022-08-24 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0003_item_color_item_size_rutinupdate_card_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_tracking',
        ),
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.CharField(default='c5pUcxZo', editable=False, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
    ]
